# This GitHub workflow performs model deployment to staging
# The workflow contents are largely the same as deploy-model-prod.yml but
# we split staging and prod model deployment into separate workflows to simplify
# separately tracking and viewing staging and prod model deployments via GitHub UI and API
#
# This workflow is triggered in an automated manner by the model training job (see notebooks/TriggerModelDeploy.py)
# after model training completes, to enable tracking and enforcing manual approval of model deployments in
# CD, if desired.
name: Staging Model Deployment for yang-mlops-project

on:
  workflow_dispatch:
    inputs:
      modelUri:
        type: string
        description: 'URI of model to deploy, in the format "models:/<model-name>/<version-id>"'
        required: true

env:
  DATABRICKS_HOST: https://adb-8405830731420074.14.azuredatabricks.net
  NODE_TYPE_ID: Standard_D3_v2
  
jobs:
  staging:
    runs-on: ubuntu-20.04
    environment: staging
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Generate AAD Token
        run: ./.github/workflows/scripts/generate-aad-token.sh ${{ secrets.STAGING_AZURE_SP_TENANT_ID }} ${{ secrets.STAGING_AZURE_SP_APPLICATION_ID }} ${{ secrets.STAGING_AZURE_SP_CLIENT_SECRET }}
      - name: Deploy model
        env:
          MLFLOW_TRACKING_URI: databricks
        run: |
          pip install mlflow
          python steps/deploy.py "${{ github.event.inputs.modelUri }}" "staging"
